[platforms.wechat.accounts.default]
article_collections = [
    "AI",
    "Agent",
    "AWS",
    "Web3",
    "DevSecOps",
    "认知思维",
    "信息安全",
    "Iac",
    "云原生"
]
video_collections = [
    "agent",
    "claude code",
    "程序员",
    "软件教程"
]
