#!/bin/bash
# Autogenerated script to monitor and download video artifact a27bc422
# From notebook 456a5a20-068a-4242-b705-0cce44b7fbdb

LOGFILE="./videos/japan_travel_english/monitor.log"
mkdir -p ./videos/japan_travel_english/
touch "$LOGFILE"

exec > >(tee -a "$LOGFILE") 2>&1

echo "Monitoring started at $(date)"
echo "Artifact: a27bc422-3460-499c-86d3-e041e16730a5"
echo "Notebook: 456a5a20-068a-4242-b705-0cce44b7fbdb"

echo "[1/2] Initial wait: sleeping 600 seconds..."
sleep 600

echo "[2/2] Starting polling loop (max 35 attempts, 60s interval)..."

for i in {1..35}
do
  echo "Attempt $i: Checking status..."
  JSON=$(notebooklm artifact list -n 456a5a20-068a-4242-b705-0cce44b7fbdb --json)
  STATUS=$(echo "$JSON" | jq -r ".artifacts[] | select(.id == \"a27bc422-3460-499c-86d3-e041e16730a5\") | .status")
  
  if [ "$STATUS" == "completed" ]; then
    echo "Status: COMPLETED. Starting download..."
    notebooklm download video ./videos/japan_travel_english/video.mp4 -a a27bc422-3460-499c-86d3-e041e16730a5 -n 456a5a20-068a-4242-b705-0cce44b7fbdb
    if [ $? -eq 0 ]; then
      echo "SUCCESS: Video downloaded to ./videos/japan_travel_english/video.mp4"
      exit 0
    else
      echo "ERROR: Download failed."
      exit 1
    fi
  elif [ "$STATUS" == "error" ] || [ "$STATUS" == "unknown" ]; then
    echo "ERROR: Artifact status is $STATUS. Stopping."
    exit 1
  fi
  
  echo "Status: $STATUS. Waiting 60s..."
  sleep 60
done

echo "FAILURE: Polling timed out after 45 minutes."
exit 1
