"""Dual-Tier Subtitle Video Generator Core Module.

Converts English/language learning text or sentences into an optimized MP4 video with:
1. Centered Primary Subtitle (current sentence/phrase for immediate focus)
2. Bottom Secondary Context Stream (previous sentence + current + next preview)

Uses Edge-TTS for timestamped speech, Pillow for card layout, and FFmpeg for concat muxing.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional

from loguru import logger
import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont


CEFR_LEVEL_PRESETS: Dict[str, Dict[str, str]] = {
    "a2": {
        "level": "a2",
        "name": "A2 Elementary",
        "tag": "A2 · ELEMENTARY",
        "rate": "-12%",
        "subtitle": "CEFR A2 Elementary · Slow & Clear Drill",
        "desc_level": "A2 Elementary",
    },
    "b1": {
        "level": "b1",
        "name": "B1 Intermediate",
        "tag": "B1 · INTERMEDIATE",
        "rate": "-6%",
        "subtitle": "CEFR B1 Intermediate · Workplace Listening",
        "desc_level": "B1 Intermediate",
    },
    "b2": {
        "level": "b2",
        "name": "B2 Professional",
        "tag": "B2 · PROFESSIONAL",
        "rate": "-3%",
        "subtitle": "CEFR B2 Professional · Fluent Immersion",
        "desc_level": "B2 Professional",
    },
    "c1": {
        "level": "c1",
        "name": "C1 Advanced",
        "tag": "C1 · ADVANCED",
        "rate": "+0%",
        "subtitle": "CEFR C1 Advanced · Native Pace Shadowing",
        "desc_level": "C1 Advanced",
    },
}


def resolve_level_preset(
    level: Optional[str] = "a2",
    rate: Optional[str] = None,
    tag: Optional[str] = None,
    subtitle: Optional[str] = None,
) -> Dict[str, str]:
    """Resolve speech rate, header tag, and subtitle based on CEFR level preset.

    Default level is 'a2'. Custom rate, tag, or subtitle will override the level presets.
    If tag is custom and lacks level prefix, the level code will be prefixed automatically.
    """
    norm_level = (level or "a2").strip().lower()
    preset = CEFR_LEVEL_PRESETS.get(norm_level, CEFR_LEVEL_PRESETS["a2"])

    resolved_rate = rate if (rate is not None and rate != "") else preset["rate"]

    if tag and tag.strip() and tag.strip() != "LISTENING PRACTICE":
        clean_tag = tag.strip()
        if not any(
            clean_tag.upper().startswith(f"{lv.upper()} ")
            or clean_tag.upper().startswith(f"{lv.upper()}·")
            or clean_tag.upper().startswith(f"{lv.upper()} ·")
            for lv in ["A2", "B1", "B2", "C1"]
        ):
            resolved_tag = f"{norm_level.upper()} · {clean_tag.upper()}"
        else:
            resolved_tag = clean_tag.upper()
    else:
        resolved_tag = preset["tag"]

    if subtitle and subtitle.strip() and subtitle.strip() not in [
        "双字幕沉浸式跟读与听力自测",
        "Dual-Subtitle Immersion & Shadowing Drill",
    ]:
        resolved_sub = subtitle.strip()
    else:
        resolved_sub = preset["subtitle"]

    return {
        "level": norm_level,
        "rate": resolved_rate,
        "tag": resolved_tag,
        "subtitle": resolved_sub,
        "desc_level": preset["desc_level"],
    }


VOICE_PRESETS: Dict[str, str] = {
    # High-quality English Male Voices
    "male": "en-US-BrianNeural",
    "brian": "en-US-BrianNeural",
    "male_mentor": "en-US-BrianNeural",
    "andrew": "en-US-AndrewNeural",
    "male_tech": "en-US-AndrewNeural",
    "guy": "en-US-GuyNeural",
    "male_news": "en-US-GuyNeural",
    "christopher": "en-US-ChristopherNeural",
    "male_authority": "en-US-ChristopherNeural",
    "ryan": "en-GB-RyanNeural",
    "male_british": "en-GB-RyanNeural",
    # High-quality English Female Voices
    "female": "en-US-JennyNeural",
    "jenny": "en-US-JennyNeural",
    "female_clear": "en-US-JennyNeural",
    "ava": "en-US-AvaNeural",
    "female_warm": "en-US-AvaNeural",
    "emma": "en-US-EmmaNeural",
    "female_conversational": "en-US-EmmaNeural",
}


def resolve_voice(voice: Optional[str] = None) -> str:
    """Resolve Edge-TTS voice identifier, allowing friendly aliases like 'male', 'brian', 'andrew'."""
    if not voice or not voice.strip():
        return "en-US-JennyNeural"
    clean_v = voice.strip()
    return VOICE_PRESETS.get(clean_v.lower(), clean_v)


def parse_time(t_str: str) -> float:
    """Parse WebVTT timestamp (HH:MM:SS.mmm or MM:SS.mmm) into seconds."""
    t_str = t_str.replace(",", ".")
    parts = t_str.split(":")
    if len(parts) == 3:
        h, m, s = float(parts[0]), float(parts[1]), float(parts[2])
        return h * 3600 + m * 60 + s
    elif len(parts) == 2:
        m, s = float(parts[0]), float(parts[1])
        return m * 60 + s
    return float(parts[0])


def parse_vtt(vtt_path: str | Path) -> List[Dict[str, Any]]:
    """Parse a WebVTT file generated by Edge-TTS into structured cues."""
    with open(vtt_path, "r", encoding="utf-8") as f:
        content = f.read()

    blocks = content.strip().split("\n\n")
    cues: List[Dict[str, Any]] = []
    time_pattern = re.compile(
        r"(\d{2}:\d{2}:\d{2}[,\.]\d{3}|\d{2}:\d{2}[,\.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,\.]\d{3}|\d{2}:\d{2}[,\.]\d{3})"
    )

    for b in blocks:
        lines = b.strip().split("\n")
        for i, line in enumerate(lines):
            m = time_pattern.search(line)
            if m:
                start = parse_time(m.group(1))
                end = parse_time(m.group(2))
                text = " ".join([l.strip() for l in lines[i + 1 :] if l.strip()])
                if text:
                    cues.append({"start": start, "end": end, "text": text})
                break
    return cues


def wrap_text(text: str, font: ImageFont.ImageFont, max_width: int, draw: ImageDraw.ImageDraw) -> List[str]:
    """Wrap text to fit within a given pixel width."""
    words = text.split()
    lines: List[str] = []
    current_line: List[str] = []
    for word in words:
        test_line = " ".join(current_line + [word])
        bbox = draw.textbbox((0, 0), test_line, font=font)
        w = bbox[2] - bbox[0]
        if w <= max_width:
            current_line.append(word)
        else:
            if current_line:
                lines.append(" ".join(current_line))
            current_line = [word]
    if current_line:
        lines.append(" ".join(current_line))
    return lines


def create_gradient_bg(
    width: int, height: int, top_hex: str = "#0B132B", bottom_hex: str = "#1C2541"
) -> Image.Image:
    """Create a high-contrast vertical linear gradient background image."""
    img = Image.new("RGB", (width, height), top_hex)
    draw = ImageDraw.Draw(img)
    r1, g1, b1 = tuple(int(top_hex.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4))
    r2, g2, b2 = tuple(int(bottom_hex.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4))
    for y in range(height):
        ratio = y / height
        r = int(r1 + (r2 - r1) * ratio)
        g = int(g1 + (g2 - g1) * ratio)
        b = int(b1 + (b2 - b1) * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))
    return img


def prepare_ambient_background(
    width: int = 1920,
    height: int = 1080,
    bg_image_path: Optional[str | Path] = None,
    blur_radius: int = 3,
    overlay_color: str = "#0B132B",
    overlay_alpha: float = 0.20,
) -> Image.Image:
    """Prepare an ambient background image with aspect-fill cropping, subtle micro-blur, and dark scrim.

    Falls back to a linear gradient if bg_image_path is not provided or cannot be loaded.
    """
    if bg_image_path:
        p = Path(bg_image_path).resolve()
        if p.exists() and p.is_file():
            try:
                img = Image.open(p).convert("RGB")
                orig_w, orig_h = img.size
                if orig_w > 0 and orig_h > 0:
                    scale = max(width / orig_w, height / orig_h)
                    new_w = int(orig_w * scale)
                    new_h = int(orig_h * scale)
                    resample_filter = getattr(Image.Resampling, "LANCZOS", Image.LANCZOS)
                    img = img.resize((new_w, new_h), resample_filter)

                    left = max(0, (new_w - width) // 2)
                    top = max(0, (new_h - height) // 2)
                    img = img.crop((left, top, left + width, top + height))

                    if blur_radius > 0:
                        img = img.filter(ImageFilter.GaussianBlur(radius=blur_radius))

                    overlay = Image.new("RGB", (width, height), overlay_color)
                    img = Image.blend(img, overlay, overlay_alpha)
                    return img
            except Exception as e:
                logger.warning(f"Failed to process ambient background image from {p}: {e}. Falling back to gradient.")

    return create_gradient_bg(width, height)


def apply_top_scrim(
    img: Image.Image,
    height: int = 150,
    start_alpha: float = 0.75,
    overlay_color: tuple[int, int, int] = (11, 19, 43),
) -> Image.Image:
    """Apply a subtle top dark-gradient scrim to guarantee header text contrast against light backgrounds."""
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw_ov = ImageDraw.Draw(overlay)
    r, g, b = overlay_color
    for y in range(height):
        alpha = int(255 * start_alpha * (1.0 - (y / height) ** 1.5))
        draw_ov.line([(0, y), (img.width, y)], fill=(r, g, b, alpha))
    return Image.alpha_composite(img.convert("RGBA"), overlay).convert("RGB")


def generate_ambient_svg(
    output_path: str | Path,
    theme: str = "tech_navy",
    width: int = 1920,
    height: int = 1080,
) -> Path:
    """Generate a modern geometric SVG with multi-color radial gradient blobs and blueprint grid."""
    out_p = Path(output_path).resolve()
    out_p.parent.mkdir(parents=True, exist_ok=True)

    svg_content = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">
  <defs>
    <radialGradient id="blob1" cx="25%" cy="35%" r="45%">
      <stop offset="0%" stop-color="#38BDF8" stop-opacity="0.45"/>
      <stop offset="100%" stop-color="#0B132B" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="blob2" cx="75%" cy="65%" r="50%">
      <stop offset="0%" stop-color="#6366F1" stop-opacity="0.38"/>
      <stop offset="100%" stop-color="#0B132B" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="blob3" cx="50%" cy="85%" r="40%">
      <stop offset="0%" stop-color="#10B981" stop-opacity="0.25"/>
      <stop offset="100%" stop-color="#0B132B" stop-opacity="0"/>
    </radialGradient>
    <pattern id="grid" width="80" height="80" patternUnits="userSpaceOnUse">
      <path d="M 80 0 L 0 0 0 80" fill="none" stroke="#1E293B" stroke-width="1.5" stroke-opacity="0.5"/>
    </pattern>
  </defs>
  <rect width="{width}" height="{height}" fill="#0B132B"/>
  <rect width="{width}" height="{height}" fill="url(#grid)"/>
  <circle cx="480" cy="380" r="450" fill="url(#blob1)"/>
  <circle cx="1440" cy="700" r="500" fill="url(#blob2)"/>
  <circle cx="960" cy="920" r="400" fill="url(#blob3)"/>
</svg>"""

    out_p.write_text(svg_content, encoding="utf-8")
    return out_p


def _get_font(size: int, bold: bool = False) -> ImageFont.ImageFont:
    """Resolve standard sans-serif font across platforms with fallback, including CJK support."""
    candidate_paths = [
        # macOS CJK & Western fonts
        "/System/Library/Fonts/Hiragino Sans GB.ttc",
        "/System/Library/Fonts/STHeiti Medium.ttc" if bold else "/System/Library/Fonts/STHeiti Light.ttc",
        "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold else "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/Library/Fonts/Arial.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for p in candidate_paths:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size)
            except Exception:
                continue
    try:
        return ImageFont.load_default()
    except Exception:
        return ImageFont.load_default()


def resolve_avatar_image(avatar_path: Optional[str | Path] = None) -> Optional[Path]:
    """Resolve presenter avatar image path, falling back to built-in avatar if available."""
    if avatar_path:
        p = Path(avatar_path).resolve()
        if p.exists():
            return p
        logger.warning(f"Specified avatar image '{avatar_path}' not found.")

    # Check default in skills/dual-subtitle-video/images/avatar_geek_studio.png
    repo_root = Path(__file__).resolve().parents[3]
    default_avatar = repo_root / "skills/dual-subtitle-video/images/avatar_geek_studio.png"
    if default_avatar.exists():
        return default_avatar
    return None


def resolve_avatar_states(base_avatar: Optional[str | Path]) -> Dict[str, Path]:
    """Find available animation states for an avatar.

    Looks for sibling files based on naming convention:
    - closed (base): <stem><suffix> (always present if base_avatar exists)
    - open: <stem>_mouth_open<suffix>, <stem>_open<suffix>
    - wide: <stem>_mouth_wide<suffix>, <stem>_wide<suffix>
    - blink: <stem>_blink<suffix>, <stem>_eyes_closed<suffix>

    Returns dict mapping state name ('closed', 'open', 'wide', 'blink') to Path.
    """
    states: Dict[str, Path] = {}
    if not base_avatar:
        return states

    p = Path(base_avatar).resolve()
    if not p.exists():
        return states

    states["closed"] = p
    stem = p.stem
    parent = p.parent
    suffix = p.suffix

    # 1. Mouth open candidates
    for cand in [
        parent / f"{stem}_mouth_open{suffix}",
        parent / f"{stem}_open{suffix}",
        parent / f"{stem}_mouth_open.png",
    ]:
        if cand.exists():
            states["open"] = cand
            break

    # 2. Mouth wide candidates
    for cand in [
        parent / f"{stem}_mouth_wide{suffix}",
        parent / f"{stem}_wide{suffix}",
        parent / f"{stem}_mouth_wide.png",
    ]:
        if cand.exists():
            states["wide"] = cand
            break

    # 3. Eyes blink candidates
    for cand in [
        parent / f"{stem}_blink{suffix}",
        parent / f"{stem}_eyes_closed{suffix}",
        parent / f"{stem}_blink.png",
    ]:
        if cand.exists():
            states["blink"] = cand
            break

    # Fallback to built-in avatar siblings if base matches default avatar name
    if len(states) == 1 and stem in ["avatar", "avatar_geek_studio"]:
        repo_root = Path(__file__).resolve().parents[3]
        default_dir = repo_root / "skills/dual-subtitle-video/images"
        for st_name, fname in [
            ("open", "avatar_geek_studio_mouth_open.png"),
            ("wide", "avatar_geek_studio_mouth_wide.png"),
            ("blink", "avatar_geek_studio_blink.png"),
        ]:
            cand = default_dir / fname
            if cand.exists() and st_name not in states:
                states[st_name] = cand

    return states


def compute_soundwave_bars(
    audio_samples: Optional[Any],
    t_start: float,
    t_end: float,
    num_bars: int = 24,
) -> List[float]:
    """Compute normalized frequency/energy levels (0.08 to 1.0) for soundwave equalizer bars."""
    if audio_samples is None or len(audio_samples) == 0:
        return [0.08] * num_bars

    s = max(0, int(t_start * 16000))
    e = min(len(audio_samples), int(t_end * 16000))
    if e <= s:
        return [0.08] * num_bars

    chunk = audio_samples[s:e]
    if len(chunk) < 64:
        return [0.08] * num_bars

    rms = float(np.sqrt(np.mean(chunk.astype(float) ** 2)))
    if rms < 180:  # silence threshold
        return [0.08] * num_bars

    fft = np.abs(np.fft.rfft(chunk))
    # Focus on speech frequency band
    usable_bins = fft[: min(len(fft), max(num_bars * 2, int(len(fft) * 0.55)))]
    splits = np.array_split(usable_bins, num_bars)

    raw_vals = [float(np.mean(b)) if len(b) > 0 else 0.0 for b in splits]
    max_v = max(raw_vals) if raw_vals and max(raw_vals) > 0 else 1.0

    loudness_gain = min(1.0, rms / 3200.0)
    bars: List[float] = []
    for val in raw_vals:
        norm = (val / max_v) * loudness_gain
        clamped = max(0.08, min(1.0, norm))
        bars.append(float(clamped))

    return bars


def render_video(
    cues: List[Dict[str, Any]],
    audio_path: str | Path,
    output_mp4: str | Path,
    title: str = "English Listening Practice",
    tag: str = "LISTENING PRACTICE",
    bg_image_path: Optional[str | Path] = None,
    bg_blur: Optional[int] = None,
    bg_alpha: Optional[float] = None,
    layout: str = "standard",
    avatar_image: Optional[str | Path] = None,
    avatar_badge: str = "AI TECH MENTOR",
    avatar_video: Optional[str | Path] = None,
) -> str:
    """Render frame cards and mux with audio into an MP4 file using FFmpeg.
    
    Supports two visual layout modes:
    - 'standard': Classic centered primary subtitle and bottom context stream.
    - 'avatar': 16:9 dual-column layout with studio presenter card and dynamic audio equalizer.
      Supports static portrait (Route 1) and Scheme B digital human neural talking-head video (avatar_video).
    """
    width, height = 1920, 1080
    temp_dir = tempfile.mkdtemp(prefix="dual_sub_")
    video_sampler: Optional[Any] = None

    try:
        is_avatar_mode = (layout or "").lower() == "avatar"
        actual_avatar: Optional[Path] = None
        av_card_base: Optional[Image.Image] = None
        av_mask = None
        card_w, card_h = 640, 870
        audio_samples: Optional[np.ndarray] = None

        font_header = _get_font(24, bold=True)
        font_title = _get_font(30 if is_avatar_mode else 32, bold=True)
        font_center = _get_font(42 if is_avatar_mode else 44, bold=True)
        font_context_label = _get_font(20, bold=True)
        font_context = _get_font(25, bold=False)
        font_context_dim = _get_font(23, bold=False)
        font_hud_title = _get_font(18, bold=True)
        font_hud_sub = _get_font(14, bold=True)

        if is_avatar_mode:
            actual_avatar = resolve_avatar_image(avatar_image)
            if not actual_avatar:
                logger.warning("Avatar layout requested but avatar image could not be resolved. Falling back to standard layout.")
                is_avatar_mode = False
            else:
                try:
                    base_raw = Image.open(actual_avatar).convert("RGB")
                    av_scale = max(card_w / base_raw.width, card_h / base_raw.height)
                    anw, anh = int(base_raw.width * av_scale), int(base_raw.height * av_scale)
                    av_resized = base_raw.resize((anw, anh), Image.Resampling.LANCZOS)
                    av_left = (anw - card_w) // 2
                    av_top = (anh - card_h) // 2
                    av_card_base = av_resized.crop((av_left, av_top, av_left + card_w, av_top + card_h)).convert("RGBA")

                    av_mask = Image.new("L", (card_w, card_h), 0)
                    av_mask_draw = ImageDraw.Draw(av_mask)
                    av_mask_draw.rounded_rectangle([0, 0, card_w, card_h], radius=24, fill=255)

                    logger.info("Studio avatar presenter card base prepared.")
                except Exception as e:
                    logger.warning(f"Failed to prepare avatar card: {e}. Falling back to standard layout.")
                    is_avatar_mode = False

            # Scheme B: Initialize VideoFrameSampler if digital human video is provided
            if is_avatar_mode and avatar_video:
                av_vid_path = Path(avatar_video).resolve()
                if av_vid_path.exists():
                    try:
                        from src.blogger.core.digital_human import VideoFrameSampler
                        video_sampler = VideoFrameSampler(av_vid_path, (card_w, card_h))
                        logger.info(f"Studio layout: using Scheme B Digital Human video stream ({av_vid_path.name})")
                    except Exception as e:
                        logger.warning(f"Failed to initialize VideoFrameSampler for {av_vid_path}: {e}")
                        video_sampler = None

            # Load audio PCM samples for real-time equalizer bars
            if is_avatar_mode and audio_path and os.path.exists(str(audio_path)):
                try:
                    ffmpeg_bin = shutil.which("ffmpeg") or "/opt/homebrew/bin/ffmpeg"
                    pcm_cmd = [ffmpeg_bin, "-i", str(audio_path), "-f", "s16le", "-ac", "1", "-ar", "16000", "-"]
                    res = subprocess.run(pcm_cmd, capture_output=True)
                    if res.returncode == 0 and res.stdout:
                        audio_samples = np.frombuffer(res.stdout, dtype=np.int16)
                        logger.info(f"Loaded {len(audio_samples)} audio samples for studio soundwave equalizer.")
                except Exception as e:
                    logger.warning(f"Failed to load audio samples for equalizer: {e}")

        blur_val = bg_blur if bg_blur is not None else (20 if is_avatar_mode else 3)
        alpha_val = bg_alpha if bg_alpha is not None else (0.45 if is_avatar_mode else 0.20)
        effective_bg_image = bg_image_path or (actual_avatar if is_avatar_mode else None)

        base_bg = prepare_ambient_background(
            width, height, bg_image_path=effective_bg_image, blur_radius=blur_val, overlay_alpha=alpha_val
        )
        base_bg = apply_top_scrim(base_bg, height=150, start_alpha=0.75)
        frame_files: List[str] = []
        durations: List[float] = []

        total_cues = len(cues)
        if total_cues == 0:
            raise ValueError("No subtitle cues provided for video rendering.")

        for idx, cue in enumerate(cues):
            duration = cue["end"] - cue["start"]
            if idx + 1 < total_cues:
                duration = cues[idx + 1]["start"] - cue["start"]
            if duration <= 0:
                duration = max(0.5, cue["end"] - cue["start"])

            img = base_bg.copy()
            draw = ImageDraw.Draw(img)

            if is_avatar_mode and av_card_base and av_mask:
                # ===================== STUDIO AVATAR DUAL-COLUMN LAYOUT =====================
                # 1. Top Header Bar
                badge_bbox = draw.textbbox((0, 0), tag, font=font_header)
                badge_w = badge_bbox[2] - badge_bbox[0]
                badge_right = max(420, 80 + 25 + badge_w + 25)
                draw.rounded_rectangle([80, 50, badge_right, 96], radius=8, fill="#1E293B", outline="#3B82F6", width=2)
                draw.text((105, 60), tag, font=font_header, fill="#60A5FA")

                draw.text((badge_right + 30, 60), title, font=font_title, fill="#F8FAFC")
                progress_str = f"{idx + 1:02d} / {total_cues:02d}"
                draw.text((width - 240, 60), progress_str, font=font_header, fill="#E2E8F0")

                # 2. Right Column: Primary Subtitle Card
                right_x1 = 760
                right_x2 = width - 80
                prim_y1 = 130
                prim_y2 = 560
                draw.rounded_rectangle([right_x1, prim_y1, right_x2, prim_y2], radius=20, fill="#1E293B", outline="#475569", width=2)
                draw.rounded_rectangle([right_x1, prim_y1, right_x1 + 12, prim_y2], radius=4, fill="#38BDF8")

                center_lines = wrap_text(cue["text"], font_center, right_x2 - right_x1 - 120, draw)
                line_height = 58
                total_text_h = len(center_lines) * line_height
                start_y = prim_y1 + (prim_y2 - prim_y1 - total_text_h) // 2
                for line in center_lines:
                    draw.text((right_x1 + 60, start_y), line, font=font_center, fill="#FFFFFF")
                    start_y += line_height

                # 3. Right Column: Context Stream Card
                ctx_y1 = 600
                ctx_y2 = 1000
                draw.rounded_rectangle([right_x1, ctx_y1, right_x2, ctx_y2], radius=18, fill="#0F172A", outline="#334155", width=2)

                draw.rounded_rectangle([right_x1 + 40, ctx_y1 + 25, right_x1 + 240, ctx_y1 + 58], radius=6, fill="#1E293B")
                draw.text((right_x1 + 55, ctx_y1 + 30), "CONTEXT STREAM", font=font_context_label, fill="#94A3B8")

                ctx_y = ctx_y1 + 88
                if idx > 0:
                    draw.polygon([(right_x1 + 45, ctx_y + 13), (right_x1 + 55, ctx_y + 7), (right_x1 + 55, ctx_y + 19)], fill="#94A3B8")
                    prev_lines = wrap_text(cues[idx - 1]["text"], font_context_dim, right_x2 - right_x1 - 120, draw)
                    draw.text((right_x1 + 75, ctx_y), prev_lines[0] if prev_lines else "", font=font_context_dim, fill="#94A3B8")
                    ctx_y += 42

                draw.polygon([(right_x1 + 45, ctx_y + 7), (right_x1 + 45, ctx_y + 21), (right_x1 + 57, ctx_y + 14)], fill="#38BDF8")
                curr_ctx_lines = wrap_text(cue["text"], font_context, right_x2 - right_x1 - 120, draw)
                draw.text((right_x1 + 75, ctx_y), curr_ctx_lines[0] if curr_ctx_lines else "", font=font_context, fill="#38BDF8")
                ctx_y += 42

                if idx + 1 < total_cues:
                    draw.text((right_x1 + 45, ctx_y), "…", font=font_context_dim, fill="#94A3B8")
                    next_lines = wrap_text(cues[idx + 1]["text"], font_context_dim, right_x2 - right_x1 - 120, draw)
                    draw.text((right_x1 + 75, ctx_y), next_lines[0] if next_lines else "", font=font_context_dim, fill="#94A3B8")

                # 4. Left Column: Studio Presenter Card with Live Equalizer Soundwave
                card_x1, card_y1 = 80, 130
                slice_step = 0.10
                num_slices = max(1, int(round(duration / slice_step)))
                actual_slice_dur = duration / num_slices
                cue_start_t = cue["start"]

                hud_x1 = 20
                bars_start_x = hud_x1 + 205
                max_bar_h = 48
                baseline_y = (card_h - 20) - 20
                bar_w = 11
                gap = 5

                for s in range(num_slices):
                    t_start = cue_start_t + s * actual_slice_dur
                    t_end = t_start + actual_slice_dur
                    bars = compute_soundwave_bars(audio_samples, t_start, t_end, num_bars=24)

                    if video_sampler is not None:
                        try:
                            slice_card = video_sampler.get_frame(t_start).convert("RGBA")
                        except Exception as e:
                            logger.warning(f"Error sampling digital human frame at t={t_start:.2f}: {e}")
                            slice_card = av_card_base.copy()
                    else:
                        slice_card = av_card_base.copy()

                    slice_card_draw = ImageDraw.Draw(slice_card)

                    # 1. Outer cyan border
                    slice_card_draw.rounded_rectangle([0, 0, card_w, card_h], radius=24, outline="#38BDF8", width=3)

                    # 2. Top Mentor Tag Pill
                    slice_card_draw.rounded_rectangle([25, 25, 230, 62], radius=8, fill="#0F172AE6", outline="#38BDF8", width=1)
                    slice_card_draw.text((40, 32), avatar_badge, font=font_hud_title, fill="#38BDF8")

                    # 3. Bottom Audio Equalizer HUD
                    hud_x1, hud_y1 = 20, card_h - 110
                    hud_x2, hud_y2 = card_w - 20, card_h - 20
                    slice_card_draw.rounded_rectangle([hud_x1, hud_y1, hud_x2, hud_y2], radius=16, fill="#0B132BEF", outline="#38BDF8", width=2)

                    # Pulse Indicator & Labels
                    slice_card_draw.ellipse([hud_x1 + 20, hud_y1 + 24, hud_x1 + 32, hud_y1 + 36], fill="#10B981")
                    slice_card_draw.text((hud_x1 + 42, hud_y1 + 20), "VOICE STREAM", font=font_hud_sub, fill="#10B981")
                    slice_card_draw.text((hud_x1 + 20, hud_y1 + 48), "SPEECH EQUALIZER", font=_get_font(12, bold=False), fill="#64748B")

                    for b_idx, level in enumerate(bars):
                        bh = max(4, int(level * max_bar_h))
                        bx = bars_start_x + b_idx * (bar_w + gap)
                        by1 = baseline_y - bh
                        by2 = baseline_y
                        if level > 0.75:
                            bcolor = "#38BDF8"  # bright cyan
                        elif level > 0.40:
                            bcolor = "#60A5FA"  # soft sky blue
                        else:
                            bcolor = "#3B82F6"  # deep blue
                        slice_card_draw.rounded_rectangle([bx, by1, bx + bar_w, by2], radius=3, fill=bcolor)

                    slice_img = img.copy()
                    slice_img.paste(slice_card, (card_x1, card_y1), av_mask)

                    frame_file = os.path.join(temp_dir, f"frame_{idx:04d}_{s:03d}.png")
                    slice_img.save(frame_file)
                    frame_files.append(frame_file)
                    durations.append(actual_slice_dur)

            else:
                # ===================== STANDARD CENTERED CARD LAYOUT =====================
                # 1. Top Header Bar
                badge_bbox = draw.textbbox((0, 0), tag, font=font_header)
                badge_w = badge_bbox[2] - badge_bbox[0]
                badge_right = max(420, 100 + 20 + badge_w + 20)
                draw.rounded_rectangle([100, 60, badge_right, 102], radius=8, fill="#1E293B", outline="#3B82F6", width=2)
                draw.text((120, 70), tag, font=font_header, fill="#60A5FA")

                title_x = badge_right + 30
                draw.text((title_x, 70), title, font=font_title, fill="#F8FAFC")
                progress_str = f"{idx + 1:02d} / {total_cues:02d}"
                draw.text((width - 240, 70), progress_str, font=font_header, fill="#E2E8F0")

                # 2. Central Primary Subtitle Card (1440px centered, balanced breathing room)
                card_x1 = 240
                card_x2 = width - 240
                center_lines = wrap_text(cue["text"], font_center, 1240, draw)
                line_height = 62
                total_text_h = len(center_lines) * line_height
                start_y = 440 - (total_text_h // 2)

                card_pad_y = 40
                card_box = [card_x1, start_y - card_pad_y, card_x2, start_y + total_text_h + card_pad_y]
                draw.rounded_rectangle(card_box, radius=18, fill="#1E293B", outline="#475569", width=2)
                draw.rounded_rectangle([card_x1, card_box[1], card_x1 + 12, card_box[3]], radius=4, fill="#38BDF8")

                curr_y = start_y
                for line in center_lines:
                    bbox = draw.textbbox((0, 0), line, font=font_center)
                    line_w = bbox[2] - bbox[0]
                    x = (width - line_w) // 2
                    draw.text((x, curr_y), line, font=font_center, fill="#FFFFFF")
                    curr_y += line_height

                # 3. Bottom Context Review Box
                bottom_box = [100, 760, width - 100, 990]
                draw.rounded_rectangle(bottom_box, radius=14, fill="#0F172A", outline="#334155", width=2)

                label_text = "CONTEXT STREAM"
                bbox_label = draw.textbbox((0, 0), label_text, font=font_context_label)
                label_w = bbox_label[2] - bbox_label[0]
                pill_pad_x = 14
                pill_right = 125 + pill_pad_x + label_w + pill_pad_x
                draw.rounded_rectangle([125, 775, pill_right, 805], radius=6, fill="#1E293B")
                draw.text((125 + pill_pad_x, 780), label_text, font=font_context_label, fill="#94A3B8")

                ctx_y = 828
                if idx > 0:
                    draw.polygon([(130, ctx_y + 13), (140, ctx_y + 7), (140, ctx_y + 19)], fill="#94A3B8")
                    prev_lines = wrap_text(cues[idx - 1]["text"], font_context_dim, 1630, draw)
                    draw.text((155, ctx_y), prev_lines[0] if prev_lines else "", font=font_context_dim, fill="#94A3B8")
                    ctx_y += 42

                draw.polygon([(130, ctx_y + 7), (130, ctx_y + 21), (142, ctx_y + 14)], fill="#38BDF8")
                curr_ctx_lines = wrap_text(cue["text"], font_context, 1630, draw)
                draw.text((155, ctx_y), curr_ctx_lines[0] if curr_ctx_lines else "", font=font_context, fill="#38BDF8")
                ctx_y += 42

                if idx + 1 < total_cues:
                    draw.text((130, ctx_y), "…", font=font_context_dim, fill="#94A3B8")
                    next_lines = wrap_text(cues[idx + 1]["text"], font_context_dim, 1630, draw)
                    draw.text((155, ctx_y), next_lines[0] if next_lines else "", font=font_context_dim, fill="#94A3B8")

                frame_file = os.path.join(temp_dir, f"frame_{idx:04d}.png")
                img.save(frame_file)
                frame_files.append(frame_file)
                durations.append(duration)

        concat_file = os.path.join(temp_dir, "concat.txt")
        with open(concat_file, "w", encoding="utf-8") as f:
            for i in range(len(frame_files)):
                f.write(f"file '{frame_files[i]}'\n")
                f.write(f"duration {durations[i]:.4f}\n")
            f.write(f"file '{frame_files[-1]}'\n")

        # Locate ffmpeg
        ffmpeg_bin = shutil.which("ffmpeg") or "/opt/homebrew/bin/ffmpeg"
        if not shutil.which("ffmpeg") and not os.path.exists(ffmpeg_bin):
            raise FileNotFoundError(f"FFmpeg binary not found at {ffmpeg_bin} or in PATH")

        output_path = Path(output_mp4).resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)

        cmd = [
            ffmpeg_bin,
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            concat_file,
            "-i",
            str(audio_path),
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-pix_fmt",
            "yuv420p",
            "-r",
            "25",
            "-c:a",
            "aac",
            "-b:a",
            "192k",
            "-shortest",
            str(output_path),
        ]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(f"FFmpeg error: {res.stderr}")

        logger.info(f"Dual-subtitle video generated successfully: {output_path}")
        return str(output_path)
    finally:
        if video_sampler is not None:
            try:
                video_sampler.close()
            except Exception:
                pass
        shutil.rmtree(temp_dir, ignore_errors=True)


def generate_dual_subtitle_video(
    input_path: str | Path,
    output_mp4: str | Path,
    voice: str = "en-US-JennyNeural",
    rate: Optional[str] = None,
    pitch: str = "+2Hz",
    title: str = "English Listening Practice",
    tag: Optional[str] = None,
    cover_path: Optional[str | Path] = None,
    subtitle: Optional[str] = None,
    bg_image: Optional[str | Path] = None,
    level: str = "a2",
    bg_blur: Optional[int] = None,
    bg_alpha: Optional[float] = None,
    layout: str = "standard",
    avatar_image: Optional[str | Path] = None,
    avatar_badge: str = "AI TECH MENTOR",
    avatar_video: Optional[str | Path] = None,
    avatar_driver: Optional[str] = None,
    generate_digital_human: bool = False,
) -> str:
    """High-level end-to-end generator pipeline: input text -> Edge-TTS speech & cues -> rendered MP4."""
    input_p = Path(input_path).resolve()
    if not input_p.exists():
        raise FileNotFoundError(f"Input file '{input_p}' does not exist.")

    cfg = resolve_level_preset(level=level, rate=rate, tag=tag, subtitle=subtitle)
    actual_rate = cfg["rate"]
    actual_tag = cfg["tag"]
    actual_sub = cfg["subtitle"]

    temp_dir = tempfile.mkdtemp(prefix="tts_sub_")
    try:
        mp3_path = os.path.join(temp_dir, "speech.mp3")
        vtt_path = os.path.join(temp_dir, "speech.vtt")

        actual_voice = resolve_voice(voice)
        logger.info(f"Synthesizing speech ({cfg['level'].upper()} rate={actual_rate}) and timestamps using {actual_voice}...")
        tts_cmd = [
            sys.executable,
            "-m",
            "edge_tts",
            f"--voice={actual_voice}",
            f"--rate={actual_rate}",
            f"--pitch={pitch}",
            "-f",
            str(input_p),
            "--write-media",
            mp3_path,
            "--write-subtitles",
            vtt_path,
        ]
        res = subprocess.run(tts_cmd, capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(f"Edge-TTS failed: {res.stderr}")

        cues = parse_vtt(vtt_path)
        logger.info(f"Parsed {len(cues)} sentence cues from {vtt_path}")

        # Scheme B: Resolve or generate Digital Human talking head video
        talking_avatar_video: Optional[Path] = None
        if avatar_video:
            av_vid_p = Path(avatar_video).resolve()
            if av_vid_p.exists():
                talking_avatar_video = av_vid_p
                logger.info(f"Using provided digital human video: {talking_avatar_video}")
        elif (generate_digital_human or avatar_driver) and (layout or "").lower() == "avatar":
            resolved_av = resolve_avatar_image(avatar_image)
            if resolved_av and resolved_av.exists():
                from src.blogger.core.digital_human import get_digital_human_driver
                driver = get_digital_human_driver(avatar_driver)
                temp_talking_mp4 = Path(temp_dir) / "avatar_talking.mp4"
                logger.info(f"Generating Scheme B digital human talking avatar with {driver.name}...")
                talking_avatar_video = driver.generate(
                    source_image=resolved_av,
                    driving_audio=mp3_path,
                    output_video=temp_talking_mp4,
                )

        rendered_mp4 = render_video(
            cues,
            mp3_path,
            output_mp4,
            title=title,
            tag=actual_tag,
            bg_image_path=bg_image,
            bg_blur=bg_blur,
            bg_alpha=bg_alpha,
            layout=layout,
            avatar_image=avatar_image,
            avatar_badge=avatar_badge,
            avatar_video=talking_avatar_video,
        )

        if cover_path:
            generate_video_cover(
                cover_path,
                title=title,
                tag=actual_tag,
                subtitle=actual_sub,
                bg_image_path=bg_image,
                bg_blur=bg_blur,
                bg_alpha=bg_alpha,
                layout=layout,
                avatar_image=avatar_image,
                avatar_badge=avatar_badge,
                avatar_video=talking_avatar_video,
            )

        return rendered_mp4
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def clean_video_title(title: str) -> str:
    """Ensure title has 0 emoji or prohibited symbols for WeChat Video compliance."""
    emoji_pattern = re.compile(r"[\U00010000-\U0010ffff]", flags=re.UNICODE)
    cleaned = emoji_pattern.sub("", title)
    cleaned = re.sub(r"[🇯🇵🎯⭐💡💯🔥🚀📌🎉✨]+", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def clean_video_desc(desc: str, default_title: str = "", level: str = "a2") -> str:
    """Ensure description length is strictly between 60 and 120 characters in English."""
    desc = desc.strip()
    preset = CEFR_LEVEL_PRESETS.get(level.lower(), CEFR_LEVEL_PRESETS["a2"])
    if len(desc) < 60:
        if default_title and len(desc) < 20:
            desc = f"Master English listening with {default_title}, featuring {preset['desc_level']} dual-tier subtitles."
        else:
            padding = f" Featuring dual-tier subtitles and {preset['desc_level']} context stream for immersion."
            desc = (desc + padding).strip()
            if len(desc) < 60:
                desc = (desc + " Ideal for daily shadowing drills.").strip()
    if len(desc) > 120:
        desc = desc[:118].rstrip("，。；！？,.!?; ") + "."
    return desc


def generate_video_cover(
    output_path: str | Path,
    title: str,
    tag: str = "A2 · ELEMENTARY",
    subtitle: str = "CEFR A2 Elementary · Slow & Clear Drill",
    width: int = 1920,
    height: int = 1080,
    bg_image_path: Optional[str | Path] = None,
    bg_blur: Optional[int] = None,
    bg_alpha: Optional[float] = None,
    layout: str = "standard",
    avatar_image: Optional[str | Path] = None,
    avatar_badge: str = "AI TECH MENTOR",
    avatar_video: Optional[str | Path] = None,
) -> Path:
    """Generate a standard 16:9 (1920x1080) video cover image for video platforms.
    
    Supports both standard hero layout and digital tutor avatar presenter layout.
    """
    out_p = Path(output_path).resolve()
    out_p.parent.mkdir(parents=True, exist_ok=True)

    is_avatar_mode = (layout or "").lower() == "avatar"
    actual_avatar: Optional[Path] = None
    if is_avatar_mode:
        actual_avatar = resolve_avatar_image(avatar_image)
        if not actual_avatar and not avatar_video:
            logger.warning("Avatar layout requested for cover but avatar image could not be resolved. Falling back to standard cover.")
            is_avatar_mode = False

    blur_val = bg_blur if bg_blur is not None else (20 if is_avatar_mode else 3)
    alpha_val = bg_alpha if bg_alpha is not None else (0.45 if is_avatar_mode else 0.20)
    effective_bg = bg_image_path or (actual_avatar if is_avatar_mode else None)

    img = prepare_ambient_background(
        width, height, bg_image_path=effective_bg, blur_radius=blur_val, overlay_alpha=alpha_val
    )
    img = apply_top_scrim(img, height=160, start_alpha=0.75)
    draw = ImageDraw.Draw(img)

    clean_t = clean_video_title(title)

    if is_avatar_mode and (actual_avatar or avatar_video):
        # ===================== AVATAR PRESENTER COVER LAYOUT =====================
        # 1. Left Column: Avatar Card
        card_x1, card_y1 = 100, 140
        card_w, card_h = 620, 820
        card_x2, card_y2 = card_x1 + card_w, card_y1 + card_h

        try:
            if avatar_video and Path(avatar_video).exists():
                from src.blogger.core.digital_human import VideoFrameSampler
                with VideoFrameSampler(avatar_video, (card_w, card_h)) as sampler:
                    av_cropped = sampler.get_frame(0.0).convert("RGBA")
            else:
                av_raw = Image.open(actual_avatar).convert("RGB")
                av_scale = max(card_w / av_raw.width, card_h / av_raw.height)
                anw, anh = int(av_raw.width * av_scale), int(av_raw.height * av_scale)
                av_resized = av_raw.resize((anw, anh), Image.Resampling.LANCZOS)
                av_left = (anw - card_w) // 2
                av_top = (anh - card_h) // 2
                av_cropped = av_resized.crop((av_left, av_top, av_left + card_w, av_top + card_h)).convert("RGBA")

            mask = Image.new("L", (card_w, card_h), 0)
            mask_draw = ImageDraw.Draw(mask)
            mask_draw.rounded_rectangle([0, 0, card_w, card_h], radius=24, fill=255)
            img.paste(av_cropped, (card_x1, card_y1), mask)
            draw.rounded_rectangle([card_x1, card_y1, card_x2, card_y2], radius=24, outline="#38BDF8", width=3)

            # Top Mentor Tag Pill
            draw.rounded_rectangle([card_x1 + 25, card_y1 + 25, card_x1 + 230, card_y1 + 62], radius=8, fill="#0F172AE6", outline="#38BDF8", width=1)
            font_av_badge = _get_font(18, bold=True)
            draw.text((card_x1 + 40, card_y1 + 32), avatar_badge, font=font_av_badge, fill="#38BDF8")

            # Bottom Audio Equalizer HUD
            hud_x1, hud_y1 = card_x1 + 20, card_y2 - 110
            hud_x2, hud_y2 = card_x2 - 20, card_y2 - 20
            draw.rounded_rectangle([hud_x1, hud_y1, hud_x2, hud_y2], radius=16, fill="#0B132BEF", outline="#38BDF8", width=2)
            draw.ellipse([hud_x1 + 20, hud_y1 + 24, hud_x1 + 32, hud_y1 + 36], fill="#10B981")
            font_hud_sub = _get_font(14, bold=True)
            draw.text((hud_x1 + 42, hud_y1 + 20), "VOICE STREAM", font=font_hud_sub, fill="#10B981")
            draw.text((hud_x1 + 20, hud_y1 + 48), "SPEECH EQUALIZER", font=_get_font(12, bold=False), fill="#64748B")

            # Cover sample preview bars
            preview_bars = [0.15, 0.45, 0.85, 0.95, 0.70, 0.80, 0.55, 0.90, 0.65, 0.40, 0.75, 0.85, 0.60, 0.35, 0.50, 0.70, 0.45, 0.30, 0.60, 0.40, 0.25, 0.20, 0.15, 0.10]
            bars_start_x = hud_x1 + 200
            max_bar_h = 48
            baseline_y = hud_y2 - 20
            bar_w = 11
            gap = 5
            for b_idx, level in enumerate(preview_bars):
                bh = max(4, int(level * max_bar_h))
                bx = bars_start_x + b_idx * (bar_w + gap)
                by1 = baseline_y - bh
                by2 = baseline_y
                bcolor = "#38BDF8" if level > 0.75 else ("#60A5FA" if level > 0.40 else "#3B82F6")
                draw.rounded_rectangle([bx, by1, bx + bar_w, by2], radius=3, fill=bcolor)
        except Exception as e:
            logger.warning(f"Failed to render avatar on cover: {e}")

        # 2. Right Column: Hero Card
        hero_x1, hero_y1 = 760, 140
        hero_x2, hero_y2 = width - 100, 960
        draw.rounded_rectangle([hero_x1, hero_y1, hero_x2, hero_y2], radius=24, fill="#1E293B", outline="#334155", width=2)
        draw.rounded_rectangle([hero_x1, hero_y1, hero_x1 + 16, hero_y2], radius=6, fill="#38BDF8")

        # Top Tag Pill
        font_badge = _get_font(24, bold=True)
        badge_text = tag.upper()
        bbox_b = draw.textbbox((0, 0), badge_text, font=font_badge)
        bw = bbox_b[2] - bbox_b[0]
        draw.rounded_rectangle([hero_x1 + 70, hero_y1 + 60, hero_x1 + 70 + bw + 50, hero_y1 + 110], radius=10, fill="#0F172A", outline="#38BDF8", width=2)
        draw.text((hero_x1 + 95, hero_y1 + 72), badge_text, font=font_badge, fill="#38BDF8")

        # Clean Title
        font_title = _get_font(50, bold=True)
        title_lines = wrap_text(clean_t, font_title, hero_x2 - hero_x1 - 140, draw)
        line_h = 68
        ty = hero_y1 + 160
        for line in title_lines:
            draw.text((hero_x1 + 70, ty), line, font=font_title, fill="#FFFFFF")
            ty += line_h

        # Subtitle
        font_sub = _get_font(28, bold=False)
        sub_y = ty + 30
        bullet_size = 8
        bx = hero_x1 + 70
        by = sub_y + 16
        draw.polygon([(bx, by - bullet_size), (bx + bullet_size, by), (bx, by + bullet_size), (bx - bullet_size, by)], fill="#38BDF8")
        draw.text((bx + 24, sub_y), subtitle, font=font_sub, fill="#94A3B8")

        # Subtle divider line inside hero card
        div_y = hero_y2 - 100
        draw.line([(hero_x1 + 70, div_y), (hero_x2 - 70, div_y)], fill="#334155", width=2)

        font_footer = _get_font(22, bold=False)
        draw.text((hero_x1 + 70, div_y + 30), "1080P FULL HD | DUAL-SUBTITLE STREAM", font=font_footer, fill="#64748B")
        draw.text((hero_x2 - 380, div_y + 30), "PIXAR 3D AVATAR MENTOR", font=font_footer, fill="#64748B")

    else:
        # ===================== STANDARD CENTERED HERO COVER =====================
        font_badge = _get_font(28, bold=True)
        font_title = _get_font(56, bold=True)
        font_sub = _get_font(34, bold=False)
        font_footer = _get_font(24, bold=False)

        # 1. Top badge tag pill
        badge_text = tag.upper()
        bbox_badge = draw.textbbox((0, 0), badge_text, font=font_badge)
        badge_w = bbox_badge[2] - bbox_badge[0]
        pill_x1, pill_y1 = 120, 100
        pill_x2, pill_y2 = pill_x1 + badge_w + 50, pill_y1 + 54
        draw.rounded_rectangle([pill_x1, pill_y1, pill_x2, pill_y2], radius=10, fill="#1E293B", outline="#38BDF8", width=2)
        draw.text((pill_x1 + 25, pill_y1 + 10), badge_text, font=font_badge, fill="#38BDF8")

        # 2. Main Center Hero Card
        card_x1, card_y1 = 120, 200
        card_x2, card_y2 = width - 120, 880
        draw.rounded_rectangle([card_x1, card_y1, card_x2, card_y2], radius=24, fill="#1E293B", outline="#334155", width=2)
        # Left accent bar
        draw.rounded_rectangle([card_x1, card_y1, card_x1 + 16, card_y2], radius=6, fill="#38BDF8")

        title_lines = wrap_text(clean_t, font_title, card_x2 - card_x1 - 160, draw)
        line_h = 76

        # Vertical centering inside hero card
        start_y = card_y1 + 120
        for line in title_lines:
            draw.text((card_x1 + 80, start_y), line, font=font_title, fill="#FFFFFF")
            start_y += line_h

        # Subtitle with cyan bullet
        sub_y = start_y + 40
        bullet_size = 8
        bx = card_x1 + 80
        by = sub_y + 20
        draw.polygon([(bx, by - bullet_size), (bx + bullet_size, by), (bx, by + bullet_size), (bx - bullet_size, by)], fill="#38BDF8")
        draw.text((bx + 24, sub_y), subtitle, font=font_sub, fill="#94A3B8")

        # Subtle divider line inside card
        div_y = card_y2 - 100
        draw.line([(card_x1 + 80, div_y), (card_x2 - 80, div_y)], fill="#334155", width=2)

        # Card footer info
        draw.text((card_x1 + 80, div_y + 30), "1080P FULL HD | DUAL-SUBTITLE STREAM", font=font_footer, fill="#64748B")
        draw.text((card_x2 - 440, div_y + 30), "FOCUS STREAM | CONTEXT HISTORY", font=font_footer, fill="#64748B")

    img.save(str(out_p), "PNG")
    logger.info(f"Video cover generated at: {out_p}")
    return out_p


def generate_video_payload_md(
    payload_dir: str | Path,
    title: str,
    desc: str,
    collection: str = "软件教程",
    author: str = "Blogger Agent",
    video_filename: str = "video.mp4",
    cover_filename: str = "cover.png",
    sentences_path: Optional[str | Path] = None,
    notes: Optional[str] = None,
    level: str = "a2",
    layout: str = "standard",
    avatar_filename: Optional[str] = None,
    avatar_video_filename: Optional[str] = None,
) -> Path:
    """Generate a standard payload.md compliant with publish-video and video platform specifications."""
    p_dir = Path(payload_dir).resolve()
    p_dir.mkdir(parents=True, exist_ok=True)
    out_md = p_dir / "payload.md"

    clean_t = clean_video_title(title)
    clean_d = clean_video_desc(desc, default_title=clean_t, level=level)

    # Validate collection
    allowed = []
    try:
        from ..config import get_wechat_collections
        allowed = get_wechat_collections(content_type="video")
    except Exception:
        try:
            from blogger.config import get_wechat_collections
            allowed = get_wechat_collections(content_type="video")
        except Exception:
            allowed = ["软件教程", "程序员", "agent", "claude code"]

    if allowed and collection not in allowed:
        logger.warning(f"Collection '{collection}' not in allowed video collections {allowed}. Defaulting to '{allowed[0]}'")
        collection = allowed[0]

    transcript_lines = []
    if sentences_path and Path(sentences_path).exists():
        with open(sentences_path, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if stripped:
                    transcript_lines.append(stripped)

    md_lines = [
        "---",
        f'title: "{clean_t}"',
        f'author: "{author}"',
        f'desc: "{clean_d}"',
        f'level: "{level.lower()}"',
        f'layout: "{layout.lower()}"',
        f'collection: "{collection}"',
        f'cover: "{cover_filename}"',
        f'video: "{video_filename}"',
    ]
    if avatar_filename:
        md_lines.append(f'avatar: "{avatar_filename}"')
    if avatar_video_filename:
        md_lines.append(f'avatar_video: "{avatar_video_filename}"')
    md_lines.extend([
        "---",
        "",
        f"# {clean_t}",
        "",
        "## Overview & Learning Objectives",
        "",
        clean_d,
        "",
    ])

    if notes:
        md_lines.extend([
            "## Key Vocabulary & Notes",
            "",
            notes.strip(),
            "",
        ])

    if transcript_lines:
        md_lines.extend([
            "## Sentence-by-Sentence Transcript",
            "",
        ])
        for idx, sentence in enumerate(transcript_lines, start=1):
            md_lines.append(f"{idx}. {sentence}")
        md_lines.append("")

    content = "\n".join(md_lines)
    out_md.write_text(content, encoding="utf-8")
    logger.info(f"Video payload.md generated at: {out_md}")
    return out_md


def create_dual_sub_payload(
    payload_dir: str | Path,
    sentences_path: str | Path,
    title: str,
    desc: str,
    collection: str = "软件教程",
    voice: str = "en-US-JennyNeural",
    rate: Optional[str] = None,
    pitch: str = "+2Hz",
    tag: Optional[str] = None,
    subtitle: Optional[str] = None,
    author: str = "Blogger Agent",
    notes: Optional[str] = None,
    bg_image: Optional[str | Path] = None,
    level: str = "a2",
    bg_blur: Optional[int] = None,
    bg_alpha: Optional[float] = None,
    layout: str = "standard",
    avatar_image: Optional[str | Path] = None,
    avatar_badge: str = "AI TECH MENTOR",
    avatar_video: Optional[str | Path] = None,
    avatar_driver: Optional[str] = None,
    generate_digital_human: bool = False,
) -> Dict[str, Any]:
    """Assemble a complete standard video payload: video.mp4, cover.png, payload.md, sentences.txt."""
    p_dir = Path(payload_dir).resolve()
    p_dir.mkdir(parents=True, exist_ok=True)

    sent_p = Path(sentences_path).resolve()
    if not sent_p.exists():
        raise FileNotFoundError(f"Sentences file not found: {sent_p}")

    dest_sent = p_dir / "sentences.txt"
    if sent_p != dest_sent:
        shutil.copy2(sent_p, dest_sent)

    cfg = resolve_level_preset(level=level, rate=rate, tag=tag, subtitle=subtitle)

    # Resolve ambient background image
    actual_bg: Optional[Path] = None
    if bg_image:
        bg_src = Path(bg_image).resolve()
        if bg_src.exists():
            dest_bg = p_dir / "bg.png"
            if bg_src != dest_bg:
                shutil.copy2(bg_src, dest_bg)
            actual_bg = dest_bg
        else:
            logger.warning(f"Specified bg_image '{bg_image}' not found.")

    if not actual_bg:
        for candidate in [p_dir / "bg.png", p_dir / "background.png"]:
            if candidate.exists():
                actual_bg = candidate
                break

    # Resolve avatar if avatar layout requested
    actual_avatar: Optional[Path] = None
    avatar_filename: Optional[str] = None
    actual_avatar_video: Optional[Path] = None
    avatar_video_filename: Optional[str] = None

    is_avatar = (layout or "").lower() == "avatar"
    if is_avatar:
        resolved_av = resolve_avatar_image(avatar_image)
        if resolved_av and resolved_av.exists():
            dest_av = p_dir / "avatar.png"
            if resolved_av != dest_av:
                shutil.copy2(resolved_av, dest_av)
            actual_avatar = dest_av
            avatar_filename = "avatar.png"

            # Copy all available avatar animation states into payload directory
            source_states = resolve_avatar_states(resolved_av)
            for st_name, st_path in source_states.items():
                if st_name == "closed":
                    continue
                if st_name == "open":
                    dest_st = p_dir / "avatar_mouth_open.png"
                elif st_name == "wide":
                    dest_st = p_dir / "avatar_mouth_wide.png"
                elif st_name == "blink":
                    dest_st = p_dir / "avatar_blink.png"
                else:
                    dest_st = p_dir / f"avatar_{st_name}.png"
                if st_path.exists() and st_path != dest_st:
                    shutil.copy2(st_path, dest_st)
        else:
            logger.warning(f"Avatar layout requested but avatar could not be resolved.")
            is_avatar = False
            layout = "standard"

        if avatar_video:
            src_av_vid = Path(avatar_video).resolve()
            if src_av_vid.exists():
                dest_av_vid = p_dir / "avatar_talking.mp4"
                if src_av_vid != dest_av_vid:
                    shutil.copy2(src_av_vid, dest_av_vid)
                actual_avatar_video = dest_av_vid
                avatar_video_filename = "avatar_talking.mp4"

    video_path = p_dir / "video.mp4"
    cover_path = p_dir / "cover.png"

    # 1. Generate video
    generate_dual_subtitle_video(
        input_path=dest_sent,
        output_mp4=video_path,
        voice=voice,
        rate=cfg["rate"],
        pitch=pitch,
        title=title,
        tag=cfg["tag"],
        bg_image=actual_bg,
        level=cfg["level"],
        bg_blur=bg_blur,
        bg_alpha=bg_alpha,
        layout=layout,
        avatar_image=actual_avatar,
        avatar_badge=avatar_badge,
        avatar_video=actual_avatar_video,
        avatar_driver=avatar_driver,
        generate_digital_human=generate_digital_human,
    )

    # If digital human video was generated during pipeline, record it
    dest_talking = p_dir / "avatar_talking.mp4"
    if dest_talking.exists():
        actual_avatar_video = dest_talking
        avatar_video_filename = "avatar_talking.mp4"

    # 2. Generate cover
    generate_video_cover(
        output_path=cover_path,
        title=title,
        tag=cfg["tag"],
        subtitle=cfg["subtitle"],
        bg_image_path=actual_bg,
        bg_blur=bg_blur,
        bg_alpha=bg_alpha,
        layout=layout,
        avatar_image=actual_avatar,
        avatar_badge=avatar_badge,
        avatar_video=actual_avatar_video,
    )

    # 3. Generate payload.md
    payload_md = generate_video_payload_md(
        payload_dir=p_dir,
        title=title,
        desc=desc,
        collection=collection,
        author=author,
        video_filename="video.mp4",
        cover_filename="cover.png",
        sentences_path=dest_sent,
        notes=notes,
        level=cfg["level"],
        layout=layout,
        avatar_filename=avatar_filename,
        avatar_video_filename=avatar_video_filename,
    )

    return {
        "payload_dir": p_dir,
        "payload_md": payload_md,
        "video_path": video_path,
        "cover_path": cover_path,
        "sentences_path": dest_sent,
        "bg_image": str(actual_bg) if actual_bg else None,
        "avatar_image": str(actual_avatar) if actual_avatar else None,
        "avatar_video": str(actual_avatar_video) if actual_avatar_video else None,
        "layout": layout,
        "level": cfg["level"],
        "rate": cfg["rate"],
        "tag": cfg["tag"],
        "title": clean_video_title(title),
        "desc": clean_video_desc(desc, title, level=cfg["level"]),
        "collection": collection,
    }
