"""Dual-Tier Subtitle Video Generator Core Module.

Converts English/language learning text or sentences into an optimized MP4 video with:
1. Centered Primary Subtitle (current sentence/phrase for immediate focus)
2. Bottom Secondary Context Stream (previous sentence + current + next preview)

Uses Edge-TTS for timestamped speech, Pillow for card layout, and FFmpeg for concat muxing.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional

from loguru import logger
from PIL import Image, ImageDraw, ImageFont


def parse_time(t_str: str) -> float:
    """Parse WebVTT timestamp (HH:MM:SS.mmm or MM:SS.mmm) into seconds."""
    t_str = t_str.replace(",", ".")
    parts = t_str.split(":")
    if len(parts) == 3:
        h, m, s = float(parts[0]), float(parts[1]), float(parts[2])
        return h * 3600 + m * 60 + s
    elif len(parts) == 2:
        m, s = float(parts[0]), float(parts[1])
        return m * 60 + s
    return float(parts[0])


def parse_vtt(vtt_path: str | Path) -> List[Dict[str, Any]]:
    """Parse a WebVTT file generated by Edge-TTS into structured cues."""
    with open(vtt_path, "r", encoding="utf-8") as f:
        content = f.read()

    blocks = content.strip().split("\n\n")
    cues: List[Dict[str, Any]] = []
    time_pattern = re.compile(
        r"(\d{2}:\d{2}:\d{2}[,\.]\d{3}|\d{2}:\d{2}[,\.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,\.]\d{3}|\d{2}:\d{2}[,\.]\d{3})"
    )

    for b in blocks:
        lines = b.strip().split("\n")
        for i, line in enumerate(lines):
            m = time_pattern.search(line)
            if m:
                start = parse_time(m.group(1))
                end = parse_time(m.group(2))
                text = " ".join([l.strip() for l in lines[i + 1 :] if l.strip()])
                if text:
                    cues.append({"start": start, "end": end, "text": text})
                break
    return cues


def wrap_text(text: str, font: ImageFont.ImageFont, max_width: int, draw: ImageDraw.ImageDraw) -> List[str]:
    """Wrap text to fit within a given pixel width."""
    words = text.split()
    lines: List[str] = []
    current_line: List[str] = []
    for word in words:
        test_line = " ".join(current_line + [word])
        bbox = draw.textbbox((0, 0), test_line, font=font)
        w = bbox[2] - bbox[0]
        if w <= max_width:
            current_line.append(word)
        else:
            if current_line:
                lines.append(" ".join(current_line))
            current_line = [word]
    if current_line:
        lines.append(" ".join(current_line))
    return lines


def create_gradient_bg(
    width: int, height: int, top_hex: str = "#0B132B", bottom_hex: str = "#1C2541"
) -> Image.Image:
    """Create a high-contrast vertical linear gradient background image."""
    img = Image.new("RGB", (width, height), top_hex)
    draw = ImageDraw.Draw(img)
    r1, g1, b1 = tuple(int(top_hex.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4))
    r2, g2, b2 = tuple(int(bottom_hex.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4))
    for y in range(height):
        ratio = y / height
        r = int(r1 + (r2 - r1) * ratio)
        g = int(g1 + (g2 - g1) * ratio)
        b = int(b1 + (b2 - b1) * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))
    return img


def _get_font(size: int, bold: bool = False) -> ImageFont.ImageFont:
    """Resolve standard sans-serif font across platforms with fallback, including CJK support."""
    candidate_paths = [
        # macOS CJK & Western fonts
        "/System/Library/Fonts/Hiragino Sans GB.ttc",
        "/System/Library/Fonts/STHeiti Medium.ttc" if bold else "/System/Library/Fonts/STHeiti Light.ttc",
        "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold else "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/Library/Fonts/Arial.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for p in candidate_paths:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size)
            except Exception:
                continue
    try:
        return ImageFont.load_default()
    except Exception:
        return ImageFont.load_default()


def render_video(
    cues: List[Dict[str, Any]],
    audio_path: str | Path,
    output_mp4: str | Path,
    title: str = "English Listening Practice",
    tag: str = "LISTENING PRACTICE",
) -> str:
    """Render frame cards and mux with audio into an MP4 file using FFmpeg."""
    width, height = 1920, 1080
    temp_dir = tempfile.mkdtemp(prefix="dual_sub_")

    try:
        font_header = _get_font(24, bold=True)
        font_title = _get_font(32, bold=True)
        font_center = _get_font(44, bold=True)
        font_context_label = _get_font(20, bold=True)
        font_context = _get_font(25, bold=False)
        font_context_dim = _get_font(23, bold=False)

        base_bg = create_gradient_bg(width, height)
        frame_files: List[str] = []
        durations: List[float] = []

        total_cues = len(cues)
        if total_cues == 0:
            raise ValueError("No subtitle cues provided for video rendering.")

        for idx, cue in enumerate(cues):
            duration = cue["end"] - cue["start"]
            if idx + 1 < total_cues:
                duration = cues[idx + 1]["start"] - cue["start"]

            img = base_bg.copy()
            draw = ImageDraw.Draw(img)

            # 1. Top Header Bar
            badge_bbox = draw.textbbox((0, 0), tag, font=font_header)
            badge_w = badge_bbox[2] - badge_bbox[0]
            badge_right = max(420, 100 + 20 + badge_w + 20)
            draw.rounded_rectangle([100, 60, badge_right, 102], radius=8, fill="#1E293B", outline="#3B82F6", width=2)
            draw.text((120, 70), tag, font=font_header, fill="#60A5FA")

            title_x = badge_right + 30
            draw.text((title_x, 70), title, font=font_title, fill="#F8FAFC")
            progress_str = f"{idx + 1:02d} / {total_cues:02d}"
            draw.text((width - 240, 70), progress_str, font=font_header, fill="#94A3B8")
            draw.line([(100, 125), (width - 100, 125)], fill="#334155", width=2)

            # 2. Central Primary Subtitle Card
            center_lines = wrap_text(cue["text"], font_center, 1500, draw)
            line_height = 62
            total_text_h = len(center_lines) * line_height
            start_y = 440 - (total_text_h // 2)

            card_pad_y = 40
            card_box = [100, start_y - card_pad_y, width - 100, start_y + total_text_h + card_pad_y]
            draw.rounded_rectangle(card_box, radius=18, fill="#1E293B", outline="#475569", width=2)
            draw.rounded_rectangle([100, card_box[1], 112, card_box[3]], radius=4, fill="#38BDF8")

            curr_y = start_y
            for line in center_lines:
                bbox = draw.textbbox((0, 0), line, font=font_center)
                line_w = bbox[2] - bbox[0]
                x = (width - line_w) // 2
                draw.text((x, curr_y), line, font=font_center, fill="#FFFFFF")
                curr_y += line_height

            # 3. Bottom Context Review Box
            bottom_box = [100, 760, width - 100, 990]
            draw.rounded_rectangle(bottom_box, radius=14, fill="#0F172A", outline="#334155", width=2)

            draw.rounded_rectangle([125, 775, 420, 805], radius=6, fill="#1E293B")
            draw.text((140, 780), "CONTEXT STREAM / 上下文回顾", font=font_context_label, fill="#94A3B8")

            ctx_y = 825
            if idx > 0:
                draw.polygon([(130, ctx_y + 13), (140, ctx_y + 7), (140, ctx_y + 19)], fill="#64748B")
                prev_lines = wrap_text(cues[idx - 1]["text"], font_context_dim, 1630, draw)
                draw.text((155, ctx_y), prev_lines[0] if prev_lines else "", font=font_context_dim, fill="#64748B")
                ctx_y += 38

            draw.polygon([(130, ctx_y + 7), (130, ctx_y + 21), (142, ctx_y + 14)], fill="#38BDF8")
            curr_ctx_lines = wrap_text(cue["text"], font_context, 1630, draw)
            draw.text((155, ctx_y), curr_ctx_lines[0] if curr_ctx_lines else "", font=font_context, fill="#38BDF8")
            ctx_y += 42

            if idx + 1 < total_cues:
                draw.text((130, ctx_y), "…", font=font_context_dim, fill="#64748B")
                next_lines = wrap_text(cues[idx + 1]["text"], font_context_dim, 1630, draw)
                draw.text((155, ctx_y), next_lines[0] if next_lines else "", font=font_context_dim, fill="#64748B")

            frame_file = os.path.join(temp_dir, f"frame_{idx:04d}.png")
            img.save(frame_file)
            frame_files.append(frame_file)
            durations.append(duration)

        concat_file = os.path.join(temp_dir, "concat.txt")
        with open(concat_file, "w", encoding="utf-8") as f:
            for i in range(len(frame_files)):
                f.write(f"file '{frame_files[i]}'\n")
                f.write(f"duration {durations[i]:.3f}\n")
            f.write(f"file '{frame_files[-1]}'\n")

        # Locate ffmpeg
        ffmpeg_bin = shutil.which("ffmpeg") or "/opt/homebrew/bin/ffmpeg"
        if not shutil.which("ffmpeg") and not os.path.exists(ffmpeg_bin):
            raise FileNotFoundError(f"FFmpeg binary not found at {ffmpeg_bin} or in PATH")

        output_path = Path(output_mp4).resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)

        cmd = [
            ffmpeg_bin,
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            concat_file,
            "-i",
            str(audio_path),
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-pix_fmt",
            "yuv420p",
            "-r",
            "25",
            "-c:a",
            "aac",
            "-b:a",
            "192k",
            "-shortest",
            str(output_path),
        ]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(f"FFmpeg error: {res.stderr}")

        logger.info(f"Dual-subtitle video generated successfully: {output_path}")
        return str(output_path)
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def generate_dual_subtitle_video(
    input_path: str | Path,
    output_mp4: str | Path,
    voice: str = "en-US-JennyNeural",
    rate: str = "-6%",
    pitch: str = "+2Hz",
    title: str = "English Listening Practice",
    tag: str = "LISTENING PRACTICE",
    cover_path: Optional[str | Path] = None,
    subtitle: str = "双字幕沉浸式跟读与听力自测",
) -> str:
    """High-level end-to-end generator pipeline: input text -> Edge-TTS speech & cues -> rendered MP4."""
    input_p = Path(input_path).resolve()
    if not input_p.exists():
        raise FileNotFoundError(f"Input file '{input_p}' does not exist.")

    temp_dir = tempfile.mkdtemp(prefix="tts_sub_")
    try:
        mp3_path = os.path.join(temp_dir, "speech.mp3")
        vtt_path = os.path.join(temp_dir, "speech.vtt")

        logger.info(f"Synthesizing speech and generating timestamps using {voice}...")
        tts_cmd = [
            sys.executable,
            "-m",
            "edge_tts",
            f"--voice={voice}",
            f"--rate={rate}",
            f"--pitch={pitch}",
            "-f",
            str(input_p),
            "--write-media",
            mp3_path,
            "--write-subtitles",
            vtt_path,
        ]
        res = subprocess.run(tts_cmd, capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(f"Edge-TTS failed: {res.stderr}")

        cues = parse_vtt(vtt_path)
        logger.info(f"Parsed {len(cues)} sentence cues from {vtt_path}")

        rendered_mp4 = render_video(cues, mp3_path, output_mp4, title=title, tag=tag)

        if cover_path:
            generate_video_cover(cover_path, title=title, tag=tag, subtitle=subtitle)

        return rendered_mp4
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def clean_video_title(title: str) -> str:
    """Ensure title has 0 emoji or prohibited symbols for WeChat Video compliance."""
    emoji_pattern = re.compile(r"[\U00010000-\U0010ffff]", flags=re.UNICODE)
    cleaned = emoji_pattern.sub("", title)
    cleaned = re.sub(r"[🇯🇵🎯⭐💡💯🔥🚀📌🎉✨]+", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def clean_video_desc(desc: str, default_title: str = "") -> str:
    """Ensure description length is strictly between 60 and 120 characters in English."""
    desc = desc.strip()
    if len(desc) < 60:
        if default_title and len(desc) < 20:
            desc = f"Master English listening with {default_title}, featuring dual-tier subtitles and live context stream."
        else:
            padding = " Featuring dual-tier subtitles and live context stream for immersive English listening practice."
            desc = (desc + padding).strip()
            if len(desc) < 60:
                desc = (desc + " Ideal for daily shadowing drills.").strip()
    if len(desc) > 120:
        desc = desc[:118].rstrip("，。；！？,.!?; ") + "."
    return desc


def generate_video_cover(
    output_path: str | Path,
    title: str,
    tag: str = "LISTENING PRACTICE",
    subtitle: str = "Dual-Subtitle Immersion & Shadowing Drill",
    width: int = 1920,
    height: int = 1080,
) -> Path:
    """Generate a standard 16:9 (1920x1080) video cover image for video platforms."""
    out_p = Path(output_path).resolve()
    out_p.parent.mkdir(parents=True, exist_ok=True)

    img = create_gradient_bg(width, height, top_hex="#0B132B", bottom_hex="#1C2541")
    draw = ImageDraw.Draw(img)

    font_badge = _get_font(28, bold=True)
    font_title = _get_font(56, bold=True)
    font_sub = _get_font(34, bold=False)
    font_footer = _get_font(24, bold=False)

    # 1. Top badge tag pill
    badge_text = tag.upper()
    bbox_badge = draw.textbbox((0, 0), badge_text, font=font_badge)
    badge_w = bbox_badge[2] - bbox_badge[0]
    pill_x1, pill_y1 = 120, 100
    pill_x2, pill_y2 = pill_x1 + badge_w + 50, pill_y1 + 54
    draw.rounded_rectangle([pill_x1, pill_y1, pill_x2, pill_y2], radius=10, fill="#1E293B", outline="#38BDF8", width=2)
    draw.text((pill_x1 + 25, pill_y1 + 10), badge_text, font=font_badge, fill="#38BDF8")

    # 2. Main Center Hero Card
    card_x1, card_y1 = 120, 200
    card_x2, card_y2 = width - 120, 880
    draw.rounded_rectangle([card_x1, card_y1, card_x2, card_y2], radius=24, fill="#1E293B", outline="#334155", width=2)
    # Left accent bar
    draw.rounded_rectangle([card_x1, card_y1, card_x1 + 16, card_y2], radius=6, fill="#38BDF8")

    # Clean title
    clean_t = clean_video_title(title)
    title_lines = wrap_text(clean_t, font_title, card_x2 - card_x1 - 160, draw)
    line_h = 76

    # Vertical centering inside hero card
    start_y = card_y1 + 120
    for line in title_lines:
        draw.text((card_x1 + 80, start_y), line, font=font_title, fill="#FFFFFF")
        start_y += line_h

    # Subtitle with cyan bullet
    sub_y = start_y + 40
    bullet_size = 8
    bx = card_x1 + 80
    by = sub_y + 20
    draw.polygon([(bx, by - bullet_size), (bx + bullet_size, by), (bx, by + bullet_size), (bx - bullet_size, by)], fill="#38BDF8")
    draw.text((bx + 24, sub_y), subtitle, font=font_sub, fill="#94A3B8")

    # Subtle divider line inside card
    div_y = card_y2 - 100
    draw.line([(card_x1 + 80, div_y), (card_x2 - 80, div_y)], fill="#334155", width=2)

    # Card footer info
    draw.text((card_x1 + 80, div_y + 30), "1080P FULL HD | DUAL-SUBTITLE STREAM", font=font_footer, fill="#64748B")
    draw.text((card_x2 - 440, div_y + 30), "FOCUS STREAM | CONTEXT HISTORY", font=font_footer, fill="#64748B")

    img.save(str(out_p), "PNG")
    logger.info(f"Video cover generated at: {out_p}")
    return out_p


def generate_video_payload_md(
    payload_dir: str | Path,
    title: str,
    desc: str,
    collection: str = "软件教程",
    author: str = "Blogger Agent",
    video_filename: str = "video.mp4",
    cover_filename: str = "cover.png",
    sentences_path: Optional[str | Path] = None,
    notes: Optional[str] = None,
) -> Path:
    """Generate a standard payload.md compliant with publish-video and video platform specifications."""
    p_dir = Path(payload_dir).resolve()
    p_dir.mkdir(parents=True, exist_ok=True)
    out_md = p_dir / "payload.md"

    clean_t = clean_video_title(title)
    clean_d = clean_video_desc(desc, default_title=clean_t)

    # Validate collection
    allowed = []
    try:
        from ..config import get_wechat_collections
        allowed = get_wechat_collections(content_type="video")
    except Exception:
        try:
            from blogger.config import get_wechat_collections
            allowed = get_wechat_collections(content_type="video")
        except Exception:
            allowed = ["软件教程", "程序员", "agent", "claude code"]

    if allowed and collection not in allowed:
        logger.warning(f"Collection '{collection}' not in allowed video collections {allowed}. Defaulting to '{allowed[0]}'")
        collection = allowed[0]

    transcript_lines = []
    if sentences_path and Path(sentences_path).exists():
        with open(sentences_path, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if stripped:
                    transcript_lines.append(stripped)

    md_lines = [
        "---",
        f'title: "{clean_t}"',
        f'author: "{author}"',
        f'desc: "{clean_d}"',
        f'collection: "{collection}"',
        f'cover: "{cover_filename}"',
        f'video: "{video_filename}"',
        "---",
        "",
        f"# {clean_t}",
        "",
        "## Overview & Learning Objectives",
        "",
        clean_d,
        "",
    ]

    if notes:
        md_lines.extend([
            "## Key Vocabulary & Notes",
            "",
            notes.strip(),
            "",
        ])

    if transcript_lines:
        md_lines.extend([
            "## Sentence-by-Sentence Transcript",
            "",
        ])
        for idx, sentence in enumerate(transcript_lines, start=1):
            md_lines.append(f"{idx}. {sentence}")
        md_lines.append("")

    content = "\n".join(md_lines)
    out_md.write_text(content, encoding="utf-8")
    logger.info(f"Video payload.md generated at: {out_md}")
    return out_md


def create_dual_sub_payload(
    payload_dir: str | Path,
    sentences_path: str | Path,
    title: str,
    desc: str,
    collection: str = "软件教程",
    voice: str = "en-US-JennyNeural",
    rate: str = "-6%",
    pitch: str = "+2Hz",
    tag: str = "LISTENING PRACTICE",
    subtitle: str = "Dual-Subtitle Immersion & Shadowing Drill",
    author: str = "Blogger Agent",
    notes: Optional[str] = None,
) -> Dict[str, Any]:
    """Assemble a complete standard video payload: video.mp4, cover.png, payload.md, sentences.txt."""
    p_dir = Path(payload_dir).resolve()
    p_dir.mkdir(parents=True, exist_ok=True)

    sent_p = Path(sentences_path).resolve()
    if not sent_p.exists():
        raise FileNotFoundError(f"Sentences file not found: {sent_p}")

    dest_sent = p_dir / "sentences.txt"
    if sent_p != dest_sent:
        shutil.copy2(sent_p, dest_sent)

    video_path = p_dir / "video.mp4"
    cover_path = p_dir / "cover.png"

    # 1. Generate video
    generate_dual_subtitle_video(
        input_path=dest_sent,
        output_mp4=video_path,
        voice=voice,
        rate=rate,
        pitch=pitch,
        title=title,
        tag=tag,
    )

    # 2. Generate cover
    generate_video_cover(
        output_path=cover_path,
        title=title,
        tag=tag,
        subtitle=subtitle,
    )

    # 3. Generate payload.md
    payload_md = generate_video_payload_md(
        payload_dir=p_dir,
        title=title,
        desc=desc,
        collection=collection,
        author=author,
        video_filename="video.mp4",
        cover_filename="cover.png",
        sentences_path=dest_sent,
        notes=notes,
    )

    return {
        "payload_dir": p_dir,
        "payload_md": payload_md,
        "video_path": video_path,
        "cover_path": cover_path,
        "sentences_path": dest_sent,
        "title": clean_video_title(title),
        "desc": clean_video_desc(desc, title),
        "collection": collection,
    }
